### ISSUE TITLE
Examples using d3-geo-polygon

### ISSUE THREAD

**Issue by Fil** [d3/d3-geo-polygon#1]
http://blockbuilder.org/Fil/90c1d39fa1b92281fd119c02188da858 shows how to use this plugin. It calls a modified version of d3.polyhedral (in d3-geo-projection) that in turn uses d3.geoClipPolygon(). More soon on this.

Older examples are available from https://bl.ocks.org/Fil/fc967d8ac6aa246863c6f2a4b7dbe41c and will be updated progressively.

Examples should go in the README when they're ready.

**Comment by Fil** [comment]
Examples _and_ a test suite with all the examples.

**Comment by Fil** [comment]
https://beta.observablehq.com/@fil/polyhedral-projections-with-d3-geo-polygon

**Comment by lightandluck** [comment]
Really looking forward to the d3.geoIcosahedral projection! Thanks so much for your work on this!
