### ISSUE TITLE
Can this library be used with other projections?

### ISSUE THREAD

**Issue by DenMesh** [d3/d3-geo-polygon#15]
Namely, d3.geoAlbers? I am trying to use preclipping and am getting very strange results.

More to the point.
Polygon 1:
`[ [ [ 30, 60 ], [ 90, 60 ], [ 90, 30 ], [ 30, 30 ], [ 30, 60 ] ] ]`
Polygon 2:
`[ [ [ 45, 75 ], [ 75, 75 ], [ 75, 15 ], [ 45, 15 ], [ 45, 75 ] ] ]`

Projection:
`d3.geoAlbers()
	.rotate([-105, 0])
	.center([-10, 65])
	.parallels([52, 64]);`

Below is a picture made in qGis, cyan polygon (P2) is being clipped, green is the one doing the clipping (P1) (the one passed to geoClipPolygon and the result passed to preclip). Both polygons are already projected (but not preclipped).
![intersection](https://user-images.githubusercontent.com/9051037/38110634-f2eb0460-33a4-11e8-8a68-b89c6bbe1e40.png)

After projecting, P2 is null.

**Comment by DenMesh** [comment]
Could you elaborate on the "geoRotation" bit? I don't quite get where to apply it.

With regards to 2D clipping, those two libraries are the reason I am trying to use this one. I have a highly "kinked" (as defined in turf) polygon that totally breaks both of them. There is a workaround, but if I can get this library to work, it may arguably be faster.

**Comment by Fil** [comment]
Yes, I've put up the code for the rotation at https://beta.observablehq.com/@fil/clipping-albers#preclip

I'd be curious to see the polygons you're working with :)

**Comment by DenMesh** [comment]
Yes, thank you, this works perfectly. As for the files, see attached archive. r.json is the clippee, p.json is the clipper. r.json is the kinked one, btw, I ended up switching them around. They are, respectively, borders of a Russian administrative subdivision and growing area of some plant species.

[geometry.zip](https://github.com/d3/d3-geo-polygon/files/1865629/geometry.zip)
