### ISSUE TITLE
Multiple broken links in examples

### ISSUE THREAD

**Issue by jimr1603** [d3/d3-geo-polygon#18]
Hi, many of the links to examples on scratchpad don't work. In particular, I want the https://beta.observablehq.com/@fil/icosahedral-projection

**Comment by Fil** [comment]
You are right, I forgot to finish and publish the icosahedral examples.
It's now available at
https://beta.observablehq.com/@fil/icosahedral-projections

I found another broken link (cubic-projection should have been
cubic-projections). Are there any others?

**Comment by jimr1603** [comment]
Thank you!  Could I bother you for a little help? I need a svg of    d3.geoIcosahedral(); and I've not much of a clue with JS. I'll have a look at the documentation all the way back to d3 tomorrow, but there's a chance you're in a timezone where it isn't bed time and you already know the answer?

**Comment by Fil** [comment]
🍪

**Comment by jimr1603** [comment]
:cookie:
