### ISSUE TITLE
d3.geoVoronoi() is not (yet) existing?

### ISSUE THREAD

**Issue by mattijn** [d3/d3-geo-polygon#19]
First, thanks for your great contributions regarding projections in `D3`. I have been playing with your new added projections in this `d3-geo-polygon` extension in combination with `vega`. Firstly I used the `airocean` projection to cut and engrave some wood using laser and liked the result¹.

But now having seen these maps on https://beta.observablehq.com/@fil/speed-of-the-voronoi-projection I would love to play with this projection as well. 

I used the method as mentioned in the notebook:

> The following map was made with the Voronoi projection — available as d3.geoVoronoi() in d3-geo-polygon.

When I try to use this:
```projection = d3.geoVoronoi()```

I receive:
```TypeError: d3.geoVoronoi is not a function```

Question: I'm trying features that are not yet available? or do I call them wrongly? 

<details>
  <summary>¹ Click to expand</summary><p>

![img_1049](https://user-images.githubusercontent.com/5186265/42728561-01859ad2-87bd-11e8-9cdf-61cd809fd2fc.jpg)
![img_1050](https://user-images.githubusercontent.com/5186265/42728562-0478cce6-87bd-11e8-981b-ac6afa3134a6.jpg)

</details>

**Comment by Fil** [comment]
Hello ! First, your images are absolutely beautiful, I would love to be able to do this too.

As for your question, that paragraph was wrong and misleading (I fixed it).

1) d3.geoVoronoi is published [here](https://github.com/Fil/d3-geo-voronoi); but it is not the voronoi projection — it's a library that helps to compute the spherical voronoi diagram.

2) the voronoi projection itself is working in private blocks, and I'm working on publishing it. In the meantime I'd be delighted to share the code with you if you want to try your lasers on it!! Please email me philippe.riviere@visionscarto.net so I can send you more details.
