### ISSUE TITLE
named imports fail in webpack build.

### ISSUE THREAD

**Issue by bmschmidt** [d3/d3-geo-polygon#23]
Trying to bundle this in a webpack-based app, I find it breaks because it assumes a hardcoded location for `node_modules` in many places, eg ([from here](https://github.com/d3/d3-geo-polygon/blob/master/src/polyhedral/index.js)).

```js
import {abs, degrees, epsilon, radians} from "../../node_modules/d3-geo-projection/src/math";
import {default as matrix, multiply, inverse} from "../../node_modules/d3-geo-projection/src/polyhedral/matrix";
```

yielding many errors like

```
ERROR in ./node_modules/d3-geo-polygon/src/polyhedral/waterman.js
Module not found: Error: Can't resolve '../../node_modules/d3-geo-projection/src/math' in '/home/bschmidt/project/node_modules/d3-geo-polygon/src/polyhedral'
```

Since I'm also requiring d3-geo-projection, these files are not inside the d3-geo-polygon folder: they're located at something like '../../../node_modules', maybe a level higher.

I'm able to get a successful install by just removing the prefix in all javascript files and importing straight from (eg) `d3-geo-projection/src/math`

```bash
~/project/node_modules/d3-geo-polygon/ find . -name "*.js" | xargs -I {} -n 1 perl -pi -e 's/\..\/\..\/node_modules\///g' {}
```
Can file a pull request if desired, but I don't know if that fix will break in other locations.

Thanks!

**Comment by mbostock** [comment]
This is a task for @Fil, but my recommendation is that these imports be removed, and instead the code is inlined in this library.

Alternatively, they should be changed to top-level exports from d3-geo-projection, and then they can be imported here, e.g.:

```js
import {polyhedralMatrix} from "d3-geo-projection";
```

**Comment by Fil** [comment]
it should work now (I inlined the code as Mike suggested)
