### ISSUE TITLE
South aspect of Lee’s conformal projection in a tetrahedron is all black

### ISSUE THREAD

**Issue by espinielli** [d3/d3-geo-polygon#28]
South aspect of Lee’s conformal projection in a tetrahedron shows all black.

![](https://pbs.twimg.com/media/D323GwTXsAAHAfu.png)

From the [tweet exchange](https://twitter.com/espinielli/status/1116249631908933632) @Fil has verified that
> it doesn't happen with d3-geo-polygon@1.7 but with d3-geo-polygon@1.8

**Comment by Fil** [comment]
Ref: https://observablehq.com/@fil/lee-projection (which I momentarily “fixed” by going back to d3-geo-polygon@1.7).

**Comment by Fil** [comment]
the bad commit is eb1e6635c35c3d21eb32c292115922205e89d153 (of course)

**Comment by Fil** [comment]
There is this quick test in https://github.com/d3/d3-geo-polygon/blob/master/src/intersect.js#L19 : two arcs of angles a.l and b.l can not intersect if the distance between start (or end) of the first and the start (or end) of the second make an angle > a.l + b.l.

I optimized it with the acos of the angles and forgot that, if A+B > pi, the cosine increases again. Fix and test incoming.

**Comment by espinielli** [comment]
you are a wizard! 
well done and thanks
