### ISSUE TITLE
Inverse clipping on d3.geoClipPolygon

### ISSUE THREAD

**Issue by saifulazfar** [d3/d3-geo-polygon#45]
Sorry noob question here...how do i inverse the clipping of d3.geoClipPolygon with preclip?...any example would be appreciate

**Comment by Fil** [comment]
I'm not sure about what you're trying to achieve, but:
- to remove a preclip, pass another clipping function ( e.g. `projection.preclip(d3.geoClipAntimeridian)`)
- to clip on the "opposite" of the clipping polygon (to reveal the contents that are clipped), inverse the winding order of the polygon.
If you have a specific example to share, I'd be happy to help.

**Comment by saifulazfar** [comment]
thank you...rewind does the trick
