### ISSUE TITLE
Tetrahedral Lee: Inverse broken?

### ISSUE THREAD

**Issue by TJung1968** [d3/d3-geo-polygon#46]
Hello,

the inverse of the Tetrahedral Lee does not seem to work.
I’ve used the script by @cambecc – [see here](https://bl.ocks.org/cambecc/eb1380f8cb0da3d4142e870a3a6b623b) – to try this. [Here is a demo](https://map-projections.net/demo/invers.php), on top is the Imago projection where the inverse works (everything’s filled with blue pixels) but on the Lee, I only get a red triangle.

Am I doing something wrong or is the inverse broken?

Kind regards,
Tobias

**Comment by Fil** [comment]
I don't know… it works here https://observablehq.com/@fil/lee-projection (works = you can drag the globe)

**Comment by TJung1968** [comment]
You’re right, it also works on [a different test](https://map-projections.net/demo/invers-2.php), where the inverse is used to get the lon/lat coordinates of the mouse pointer position. So I guess it’s a problem of the script calling the inverse rather than the inverse itself.
