### ISSUE TITLE
rhombic dodecahedron test produces weird results probably something i am missing

### ISSUE THREAD

**Issue by bathoorn** [d3/d3-geo-polygon#58]
So i was trying to create a rhombic dodecahedron projection but there is something weird going on with the clipping

```
rhombic_f = {
  var degrees = 180 / Math.PI;
  var phi1 = Math.atan(Math.SQRT1_2) * degrees;
  var vertices = [
    [0, 90],      // 0
    [0, phi1],    // 1
    [90, phi1],   // 2
    [180, phi1],  // 3
    [-90, phi1],  // 4
    [45, 0],      // 5
    [135, 0],     // 6
    [-135, 0],     // 7
    [-45, 0],     // 8
    [0, -phi1],   // 9
    [90, -phi1],  // 10
    [180, -phi1], // 11
    [-90, -phi1], // 12
    [0, -90]      // 13
  ];
    
  // rhombic dodecahedron
  var polyhedron = [
    [0, 1, 8, 4],
    [0, 2, 5, 1],
    [0, 3, 6, 2],
    [0, 4, 7, 3],

    [1, 5, 9, 8],
    [2, 6, 10, 5],
    [3, 7, 11, 6],
    [4, 8, 12, 7],

    [8, 9, 13, 12],
    [5, 10, 13, 9],
    [6, 11, 13, 10],
    [7, 12, 13, 11]
  ].map(function(face) {
          return face.map(function(i) {
            return vertices[i];
          });
  });

  var polygons = {
    type: "FeatureCollection",
    features: polyhedron.map(function(face) {
      face.push(face[0]);
      return {
        properties: { sitecoordinates: d3.geoCentroid({type:"MultiPoint", coordinates: face}) },
        geometry: {
          type: "Polygon",
          coordinates: [ face ]
        }
      };
    })
  };

var parents = [
      -1, // 0
      0, // 1
      6, // 2
      2, // 3
      1, // 4
      9, // 5
      11, // 6
      3, // 7
      4, // 8
      8, // 9
      5, // 10
      10, // 11
    ];

  //return polygons;
  return d3.geoPolyhedralVoronoi()
   .parents(parents)
   .polygons(polygons);
};
```

i numbered the faces in the image below and there should be red lines around all the faces. This is a combination of the cubic and the octahedron projection. 

<img width="1164" alt="image" src="https://github.com/d3/d3-geo-polygon/assets/760615/82f21f7e-7495-4a6e-93ab-48e47cbc1af5">

**Comment by bathoorn** [comment]
maybe it helps to have something a bit more recognizable

<img width="1166" alt="image" src="https://github.com/d3/d3-geo-polygon/assets/760615/7467ab93-5a57-4005-b26a-82b27ace1b0b">

i have seen artifacts like this before when i did not calculate the parent list correctly but i think it is correct. some faces just seem to be split up over several parts of the map. I can't figure out why.

**Comment by Fil** [comment]
Yes this shows a bug in my code: the centroid is wrong, as it counts `face[0]` twice. To fix, we should remove `face.push(face[0])`, and instead do `coordinates: [[...face, face[0]]]` in the polygon geometry.
<img width="801" alt="Capture d’écran 2024-06-04 à 10 49 16" src="https://github.com/d3/d3-geo-polygon/assets/7001/4d373cfb-c80f-490e-88c9-fe74929d98c7">

(Alternatively, use `LineString` instead of `MultiPoint` in the geoCentroid.)

**Comment by bathoorn** [comment]
wow yes that is exactly what i was trying to do :)

**Comment by bathoorn** [comment]
woohoo, made the change to my observablehq as well

<img width="1173" alt="image" src="https://github.com/d3/d3-geo-polygon/assets/760615/3c82ab1a-1fa6-47ca-b402-b53e4f23dbf4">
