### ISSUE TITLE
is it possible to only draw some of the faces?

### ISSUE THREAD

**Issue by bathoorn** [d3/d3-geo-polygon#62]
i can only draw the first face by setting .parents([-1])

but if i only wanted to draw for example the first 3 faces of a cube would that be possible?

i have this question as i like to laser cut the faces out of would an turn them into a globe.
Drawing only a few faces would make it easier to fit on the laser cutter.

**Comment by Fil** [comment]
yes, if you change `parents` you can make an incomplete tree

**Comment by bathoorn** [comment]
so for the rombic i can do this
rhombic.parents([-1, 0, 6, 2, 1, 9, 11, 3, 4, 8, 6, 10, ])
which will give me only the firtst 6 faces the rest are simply not connected to this

<img width="824" alt="image" src="https://github.com/d3/d3-geo-polygon/assets/760615/e64a2082-b242-4984-9a21-50f7e1d7f086">

for the next 6 faces doing this
rhombic_f.parents([4, 0, 6, 2, 1, 9, 11, 3, 4, 8, -1, 10, ]) result in this error: RangeError: Maximum call stack size exceeded.
I must be doing something wrong there, but i can't seem to find what

the original parent list is this
parents = [
      -1, // 0
      0, // 1
      6, // 2
      2, // 3
      1, // 4
      9, // 5
      11, // 6
      3, // 7
      4, // 8
      8, // 9
      5, // 10
      10, // 11
    ];

**Comment by bathoorn** [comment]
oh i figured it out parent 0 is always the root and should have value -1

so i have to reorganize the faces for that to work

**Comment by Fil** [comment]
Yes—not super easy to manipulate, I agree.

**Comment by bathoorn** [comment]
Well it does what it is supposed to do really well. My use case is not really what it was made for. But it can be done.

I think this can be closed.

**Comment by bathoorn** [comment]
It works by reordering the faces.
