### ISSUE TITLE
Clipping artefacts on rotate

### ISSUE THREAD

**Issue by espinielli** [d3/d3-geo-polygon#7]
I was playing around and got some clipping problem.
This code `map(d3.geoCubic().parents([-1, 2, 0, 2, 5, 2]).rotate([0,0,45]))` produces some artefacts:
![screen shot 2018-03-18 at 3 50 41 pm](https://user-images.githubusercontent.com/891692/37567243-5b61c23e-2ac4-11e8-871f-ffaff9be1e75.png)

`map()` as per https://beta.observablehq.com/@fil/polyhedral-projections-with-d3-geo-polygon

**Comment by Fil** [comment]
In this case intersect() doesn't spot _any_ intersection. Branch https://github.com/d3/d3-geo-polygon/tree/intersect2 fixes this particular situation, but I'm not satisfied by the solution.

**Comment by Fil** [comment]
The solution in that branch doesn't fix `map(d3.geoDodecahedral().rotate([0,0]))` and even makes it worse.
https://beta.observablehq.com/@fil/dev-broken-projections
Some more research is needed :)

**Comment by Fil** [comment]
AT LAST! FIXED!

See https://beta.observablehq.com/@fil/spherical-intersection for the edge cases that were causing some lines to escape the clipping polygon.
