### ISSUE TITLE
Tried adding parents to TetrahedralLee

### ISSUE THREAD

**Issue by bathoorn** [d3/d3-geo-polygon#70]
Hi,

i made some changes to TetrahedralLee so i can add parents and it also supports setting the root of the tree in other places than faces[0]. I added it to my fork [here](https://github.com/bathoorn/d3-geo-polygon/blob/master/src/tetrahedralLee.js) if you want to see.

Here are some images created whith the snapshot unittests

![tetra1](https://github.com/d3/d3-geo-polygon/assets/760615/b160ae81-3e22-4777-9176-6843ed6d2f9e)
![tetra2](https://github.com/d3/d3-geo-polygon/assets/760615/d0c09143-acce-4799-9e6e-afe3ab29ccb5)
![tetra3](https://github.com/d3/d3-geo-polygon/assets/760615/4aadf682-4ffa-4b40-855a-d647fb0774fb)
![tetra4](https://github.com/d3/d3-geo-polygon/assets/760615/4dadadd2-d787-4a1f-8a5c-98bf7ab89aec)

i also tried generating svg's but that is not working flawless yet.

**Comment by bathoorn** [comment]
And the code of the snapshots

```
export async function tetra1() {
  return renderWorld(
    geoTetrahedralLee()
      .parents([-1, 3, 1, 2])
      .rotate([115, -54.735610317245346, 90])
      .precision(0.1)
      .fitSize([width, height], { type: "Sphere" })
  );
}

export async function tetra2() {
  return renderWorld(
    geoTetrahedralLee()
      .parents([2, -1, 3, 0])
      .angle(90)
      .rotate([115, -54.735610317245346, 90])
      .precision(0.1)
      .fitSize([width, height], { type: "Sphere" })
  );
}

export async function tetra3() {
  return renderWorld(
    geoTetrahedralLee()
      .parents([3, 0, -1, 1])
      .angle(-30)
      .rotate([115, -54.735610317245346, 90])
      .precision(0.1)
      .fitSize([width, height], { type: "Sphere" })
  );
}

export async function tetra4() {
  return renderWorld(
    geoTetrahedralLee()
      .parents([1, 2, 0, -1])
      .angle(210)
      .rotate([115, -54.735610317245346, 90])
      .precision(0.1)
      .fitSize([width, height], { type: "Sphere" })
  );
}
```

**Comment by Fil** [comment]
Are you generating an isolated face? I believe you can solve this with leeRaw directly—without having to go through the polyhedral transform.

However, I do understand adding a parents method if the goal is to detach a side triangle and reattach it to another side, like so:

```
 ▲
△▽△    =>    △▽△▼
```

**Comment by bathoorn** [comment]
Yes i was trying to get isolated faces so i can get them in the laser cutter easier.
For most of the other polyhedrons this worked but tetrahedralLee did not support the parents.
This indeed also allows different cofigurations which might save on wood when cutting.

I will see if i can also get this to work with leeRaw.

**Comment by bathoorn** [comment]
that is a nice one recreating it with the voronoi function.

**Comment by bathoorn** [comment]
works great! 

I got some little artifacts in the red lines but that is something i do myself using geoInterpolate to draw all the edges of all the faces.

<img width="1505" alt="image" src="https://github.com/d3/d3-geo-polygon/assets/760615/bc6288e3-0114-4a20-b707-5ddb8c713596">

**Comment by Fil** [comment]
Yes, the raw projection is quite unstable at this vertex — you can use a straight line connecting the projected vertices rather than line interpolation.

**Comment by bathoorn** [comment]
this is what i used it for :)

![IMG20240630155425](https://github.com/d3/d3-geo-polygon/assets/760615/c60cfc18-72e6-4baa-a000-caa4db02d845)
![IMG20240630155439](https://github.com/d3/d3-geo-polygon/assets/760615/e265a8eb-dd85-4c8c-88a8-00ff4a853a43)
